# Site settings
title: Code Recollection
email: guydavis.ca@gmail.com
copyright_name: Guy Davis
description: "Notes from my explorations in Computer Science"
baseurl: ""
url: "https://guydavis.github.io"

# Social links
# twitter_username: 
github_username:  guydavis
linkedin_username: guydavis
# facebook_username:
email_username:  guydavis.ca@gmail.com
slideshare_username: guy_davis
stack_overflow_userpath: 3072265/guy-davis

# Disqus comments
enable_disqus: true
disqus_shortname: guydavis

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
enable_ga: true
google_analytics: G-275Q9942PK

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
