# Site settings
title: Code Recollection
header-img: img/ohara.jpg
email: guydavis.ca@gmail.com
copyright_name: Guy Davis
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://guydavis.ca"
#twitter_username: 
github_username:  guydavis
#facebook_username:  
email_username:  guydavis.ca@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
